import React, { useEffect, useState } from 'react'
import { useParams } from 'react-router'
import { getSharedReport } from '../services/interview.api'
import '../style/shared.scss'

const SharedReport = () => {
    const { token } = useParams()
    const [report, setReport] = useState(null)
    const [loading, setLoading] = useState(true)
    const [error, setError] = useState(null)

    useEffect(() => {
        getSharedReport(token)
            .then(d => setReport(d.interviewReport))
            .catch(() => setError('This report link is invalid or has expired.'))
            .finally(() => setLoading(false))
    }, [token])

    if (loading) return <main className='loading-screen'><h1>Loading shared report...</h1></main>
    if (error) return (
        <main className='shared-error'>
            <div className='shared-error__box'>
                <span>🔗</span>
                <h2>Link Not Found</h2>
                <p>{error}</p>
            </div>
        </main>
    )

    const scoreColor = report.matchScore >= 80 ? 'high' : report.matchScore >= 60 ? 'mid' : 'low'

    return (
        <div className='shared-page'>
            <header className='shared-header'>
                <div className='shared-header__brand'>⚡ InterviewAI</div>
                <div className='shared-header__badge'>📤 Shared Report</div>
            </header>

            <div className='shared-body'>
                <div className='shared-title-row'>
                    <h1>{report.title}</h1>
                    <div className={`shared-score score--${scoreColor}`}>
                        <span className='shared-score__val'>{report.matchScore}</span>
                        <span className='shared-score__pct'>%</span>
                    </div>
                </div>

                <div className='shared-sections'>
                    {/* Skill Gaps */}
                    <section className='shared-section'>
                        <h2>Skill Gaps</h2>
                        <div className='shared-gaps'>
                            {report.skillGaps.map((g, i) => (
                                <span key={i} className={`skill-tag skill-tag--${g.severity}`}>{g.skill}</span>
                            ))}
                        </div>
                    </section>

                    {/* Technical Questions */}
                    <section className='shared-section'>
                        <h2>Technical Questions ({report.technicalQuestions.length})</h2>
                        <ul className='shared-qlist'>
                            {report.technicalQuestions.map((q, i) => (
                                <li key={i} className='shared-qitem'>
                                    <strong>Q{i + 1}:</strong> {q.question}
                                </li>
                            ))}
                        </ul>
                    </section>

                    {/* Behavioral Questions */}
                    <section className='shared-section'>
                        <h2>Behavioral Questions ({report.behavioralQuestions.length})</h2>
                        <ul className='shared-qlist'>
                            {report.behavioralQuestions.map((q, i) => (
                                <li key={i} className='shared-qitem'>
                                    <strong>Q{i + 1}:</strong> {q.question}
                                </li>
                            ))}
                        </ul>
                    </section>

                    {/* Preparation Plan */}
                    <section className='shared-section'>
                        <h2>Preparation Roadmap</h2>
                        <div className='shared-roadmap'>
                            {report.preparationPlan.map(day => (
                                <div key={day.day} className='shared-day'>
                                    <div className='shared-day__header'>
                                        <span className='shared-day__badge'>Day {day.day}</span>
                                        <strong>{day.focus}</strong>
                                    </div>
                                    <ul>{day.tasks.map((t, i) => <li key={i}>{t}</li>)}</ul>
                                </div>
                            ))}
                        </div>
                    </section>
                </div>

                <footer className='shared-footer'>
                    <p>Generated by <strong>InterviewAI</strong> · This is a read-only shared view</p>
                </footer>
            </div>
        </div>
    )
}

export default SharedReport
